In [50]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Join

In [51]:
billionaires = Table.read_table('billionaires.csv')
billionaires.show(10)

countries = Table.read_table('countries.csv')
countries.show(10)

### What can we join these two tables on?

In [4]:
billionaires.join('citizenship', countries, 'Country')

citizenship | name                | net worth   | industry        | Continent
Australia   | Gina Rinehart       | 19984845036 | Commodities     | Oceania
Australia   | Andrew Forrest      | 10221458789 | Commodities     | Oceania
Australia   | Harry Triguboff     | 9467000000  | Real Estate     | Oceania
Australia   | Scott Farquhar      | 9335988154  | Technology      | Oceania
Australia   | Mike Cannon-Brookes | 9335988154  | Technology      | Oceania
Australia   | Frank Lowy          | 6655432824  | Real Estate     | Oceania
Australia   | Anthony Pratt       | 6566000000  | Industrial      | Oceania
Austria     | Dietrich Mateschitz | 12251315379 | Food & Beverage | Europe
Austria     | Johann Graf         | 6509183360  | Entertainment   | Europe
Brazil      | Jorge Paulo Lemann  | 23056345424 | Food & Beverage | South America
... (490 rows omitted)

In [5]:
billionaires.join('citizenship', countries, 'Continent')

In [6]:
countries.join('Country', billionaires, 'citizenship')

Country   | Continent     | name                | net worth   | industry
Australia | Oceania       | Gina Rinehart       | 19984845036 | Commodities
Australia | Oceania       | Andrew Forrest      | 10221458789 | Commodities
Australia | Oceania       | Harry Triguboff     | 9467000000  | Real Estate
Australia | Oceania       | Scott Farquhar      | 9335988154  | Technology
Australia | Oceania       | Mike Cannon-Brookes | 9335988154  | Technology
Australia | Oceania       | Frank Lowy          | 6655432824  | Real Estate
Australia | Oceania       | Anthony Pratt       | 6566000000  | Industrial
Austria   | Europe        | Dietrich Mateschitz | 12251315379 | Food & Beverage
Austria   | Europe        | Johann Graf         | 6509183360  | Entertainment
Brazil    | South America | Jorge Paulo Lemann  | 23056345424 | Food & Beverage
... (490 rows omitted)

In [52]:
b_and_c = billionaires.join('citizenship', countries, 'Country')

In [12]:
b_and_c.group('Continent')

Continent     | count
Africa        | 7
Asia          | 168
Europe        | 111
North America | 192
Oceania       | 8
South America | 14

##### Question: How many billionaries are in a specific industry and Continent?

_Hint: Is there a way we can format the data to see this easily?_

In [13]:
b_and_c.labels

('citizenship', 'name', 'net worth', 'industry', 'Continent')

In [ ]:
b_and_c.group(['Continent', 'industry']).barh('industry', 'count')

In [17]:
b_and_c.group(['Continent', 'industry'])

Continent | industry        | count
Africa    | Diversified     | 2
Africa    | Food & Beverage | 1
Africa    | Industrial      | 2
Africa    | Media & Telecom | 2
Asia      | Commodities     | 7
Asia      | Consumer        | 10
Asia      | Diversified     | 27
Asia      | Energy          | 12
Asia      | Entertainment   | 4
Asia      | Finance         | 4
... (46 rows omitted)

In [15]:
b_and_c.pivot('Continent', 'industry')

industry        | Africa | Asia | Europe | North America | Oceania | South America
Commodities     | 0      | 7    | 1      | 6             | 2       | 2
Consumer        | 0      | 10   | 17     | 14            | 0       | 0
Diversified     | 2      | 27   | 13     | 10            | 0       | 0
Energy          | 0      | 12   | 1      | 17            | 0       | 0
Entertainment   | 0      | 4    | 4      | 9             | 0       | 0
Finance         | 0      | 4    | 1      | 29            | 1       | 6
Food & Beverage | 1      | 11   | 9      | 14            | 0       | 4
Health Care     | 0      | 11   | 10     | 6             | 0       | 0
Industrial      | 2      | 21   | 21     | 4             | 1       | 1
Media & Telecom | 2      | 3    | 4      | 19            | 0       | 0
... (4 rows omitted)

##### Question: What is the average net worth of the billionaries in each specific industry and Continent?

In [22]:
b_and_c.pivot('Continent', 'industry', 'net worth', np.average)

industry        | Africa      | Asia        | Europe      | North America | Oceania     | South America
Commodities     | 0           | 1.03705e+10 | 9.09765e+09 | 6.89452e+09   | 1.51032e+10 | 1.00079e+10
Consumer        | 0           | 8.03002e+09 | 2.10536e+10 | 9.61956e+09   | 0           | 0
Diversified     | 7.29722e+09 | 1.01818e+10 | 8.05679e+09 | 2.51075e+10   | 0           | 0
Energy          | 0           | 1.50254e+10 | 7.09577e+09 | 6.72667e+09   | 0           | 0
Entertainment   | 0           | 7.96645e+09 | 5.39832e+09 | 1.05302e+10   | 0           | 0
Finance         | 0           | 8.79806e+09 | 8.31946e+09 | 8.92508e+09   | 7.07147e+09 | 9.0227e+09
Food & Beverage | 6.15496e+09 | 9.40541e+09 | 1.04686e+10 | 1.27264e+10   | 0           | 1.41998e+10
Health Care     | 0           | 8.79122e+09 | 5.72663e+09 | 1.00891e+10   | 0           | 0
Industrial      | 1.16792e+10 | 9.31591e+09 | 1.01403e+10 | 3.71755e+10   | 6.566e+09   | 5.36317e+09
Media & Telecom | 4.91348e+09 | 7.12921e+09 | 7.5358e+09  | 8.63351e+09   | 0           | 0
... (4 rows omitted)

##### Question: What is the range of net worths of the billionaries in each specific industry and Continent?
_Hint: It may be helpful to define a function that will compute the range_

In [25]:
b_and_c.where('industry', 'Finance').where('citizenship', 'Brazil').column('net worth')

array([18458658992,  6253267126,  5869914091,  5868875957,  5844914091])

In [26]:
max(b_and_c.where('industry', 'Finance').where('citizenship', 'Brazil').column('net worth'))

18458658992

In [27]:
min(b_and_c.where('industry', 'Finance').where('citizenship', 'Brazil').column('net worth'))

5844914091

In [53]:
def range(x):
    "Given as input an array of numerical values, compute the range"
    return max(x) - min(x)

In [31]:
range(b_and_c.where('industry', 'Finance').where('Continent', 'North America').column('net worth'))

16675000000

In [54]:
b_and_c.group(['Continent', 'industry'])

Continent | industry        | count
Africa    | Diversified     | 2
Africa    | Food & Beverage | 1
Africa    | Industrial      | 2
Africa    | Media & Telecom | 2
Asia      | Commodities     | 7
Asia      | Consumer        | 10
Asia      | Diversified     | 27
Asia      | Energy          | 12
Asia      | Entertainment   | 4
Asia      | Finance         | 4
... (46 rows omitted)

In [57]:
max(b_and_c.where('Continent', 'Africa').where('industry', 'Diversified').column('net worth')) - min(b_and_c.where('Continent', 'Africa').where('industry', 'Diversified').column('net worth'))

144439667

In [65]:
b_and_c.where('Continent', 'Asia').where('industry', 'Diversified').column('net worth')

array([10510596219,  4890503505,  7045776781,  5542702192, 17958700040,
       16902192777,  6563948173,  6425000000, 20694315362,  7162832884,
       16688134027,  5602195158,  4542419459,  6817029460, 17353026306,
       16419785817, 16409338374, 13809163245, 11487952601,  9678266079,
        9340111446,  7089777594,  5767367272, 14834293002,  5196300702,
        5108740243,  5069047637])

In [61]:
max(x) - min(x)

144439667

In [64]:
range(x)

16151895903

In [30]:
b_and_c.pivot('Continent', 'industry', 'net worth', range)

industry        | Africa     | Asia        | Europe      | North America | Oceania    | South America
Commodities     | 0          | 25994346585 | 0           | 6657486568    | 9763386247 | 9287846319
Consumer        | 0          | 18140260370 | 97829900975 | 32594498452   | 0          | 0
Diversified     | 144439667  | 16151895903 | 13744837738 | 84824453185   | 0          | 0
Energy          | 0          | 53802123350 | 0           | 5804927881    | 0          | 0
Entertainment   | 0          | 12875609983 | 1956683360  | 33551074956   | 0          | 0
Finance         | 0          | 9330824516  | 0           | 16675000000   | 0          | 12613744901
Food & Beverage | 0          | 13271409969 | 27957741703 | 38923396269   | 0          | 13309113752
Health Care     | 0          | 10286113710 | 3025420091  | 10732971607   | 0          | 0
Industrial      | 9653384976 | 17078158803 | 17430120357 | 55467867869   | 0          | 0
Media & Telecom | 404797480  | 4466691044  | 7754892015  | 22213134469   | 0          | 0
... (4 rows omitted)

In [66]:
b_and_c.group(['Continent', 'industry'], range)

Continent | industry        | citizenship range | name range | net worth range
Africa    | Diversified     |                   |            | 144439667
Africa    | Food & Beverage |                   |            | 0
Africa    | Industrial      |                   |            | 9653384976
Africa    | Media & Telecom |                   |            | 404797480
Asia      | Commodities     |                   |            | 25994346585
Asia      | Consumer        |                   |            | 18140260370
Asia      | Diversified     |                   |            | 16151895903
Asia      | Energy          |                   |            | 53802123350
Asia      | Entertainment   |                   |            | 12875609983
Asia      | Finance         |                   |            | 9330824516
... (46 rows omitted)

# Comparison

In [32]:
x = 2
y = 3

In [33]:
x > 1

True

In [34]:
x > y

False

In [38]:
x != y

True

### Comparing strings

In [39]:
"dog" == "dog"

True

In [42]:
# DO not recommend doing these types of comparisons
"dog" > "cat"

True

In [41]:
"z" > "y"

True

In [43]:
"dogma" == "dog"

False

### Comparisions to arrays

In [44]:
range_between_one_twenty = np.arange(1, 20)

In [45]:
range_between_one_twenty

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [46]:
range_between_one_twenty > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [47]:
True == 1

True

In [48]:
False == 0

True

In [49]:
sum(range_between_one_twenty > 3)

16

### Combining comparisons

### Aggregating Comparisons

# Control Statements

### `if`, `elif`, and `else`

### `abs()`
Let's try implementing the `abs()` function using `if`, `elif`, and `else`.