In [1]:
from datascience import *
import numpy as np
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
plots.rcParams["patch.force_edgecolor"] = True

### Last Class's Survey

As always, Python reference sheet: https://data8.org/fa26/reference/

In [2]:
survey = Table.read_table('class_survey.csv')

## Histograms continued

Last time we loaded how long the highest grossing movies of 2017 had been out (in years) as of 2026.

In [31]:
top_movies = Table.read_table('top_movies_2017.csv')
top_movies.show(6)

We then calculated the ages of each movie and updated our `top_movies` table to include a column with the ages of each movie.

In [32]:
ages = 2026 - top_movies.column('Year')
top_movies = top_movies.with_column('Age', ages)

array([ 87,  49,  61,  44,  29,  70,  51,  61,  53,  89,  11,  65,  46,
        67,  17,  43,  33,  27,  32,  53,  45,  59,  85,  11,  54,  32,
        62,  48,  14,  61,  18,  59,  67,  42,  22,  57,  56,  24,  30,
        36,  86,  63,  42,  62,  56,  53,  73,  20,  70,  84,  52,  37,
        81,  23,  23,  52,  10,  76,  22,  74,  62,  48,  22,  21,  41,
        24,  14,  27,  48,  44,  49,   9,  10,  65,  25,  71,  49,  64,
        51,  50,  80,  54,  25,  30,  29,  69,  17,  63,  66,  51,  56,
        42,  11,  24,  33,  34,  16,  36,  13,  80,  14,  23,  73,  72,
        29,  37,  25,  13,  19,  13,  35,  85,  26,  40,  15,  27,  25,
        19,  13,  10,  23,  19,  40, 105,  28,   9,  52,  73,  42,  35,
        21,  21,  19,  24,  33,  72,  18,  15,  22,  18,  31,   9,  36,
        44,  58,  38,  10,  59,  11,  12,  47,  28,  66,  44,  19,  41,
        31,  10,  36,  52,  16,  22,  26,  34,  10,  39,  24,  12,  11,
        30,  12,  11,  49,  45,  27,  17,  23,  22,  58,  26,  25,  31,
        56,  39,  10,  29,  35,  39,  16,  17,  34,  24,  45,  17,  54,
        46,  10,  33,  10,  38])

In [34]:
top_movies.select('Title', 'Age').show(6)

Running `top_movies.hist('Age')` we were able to produce a histogram with 10 equally sized bins

In [ ]:
### This is where we stopped last time. 
top_movies.hist('Age')

### Functions

### `apply`

In [ ]:
fam = Table().with_columns(
    'First Name', make_array('Jeremy', 'Olivia', 'Barnard'),
    'Birth Year', make_array(1999, 2005, 2015)
)
fam